name: Execute plotting_and_stats_example

env:
  DEVOPS_DIR: plotting_maps

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: /plotting_maps/requirements.txt
      - name: execute py script
        run: python plotting_and_stats_examples.py
        
      # - uses: actions/upload-artifact@v3
      #   if: always()
      
