name: Execute plotting_and_stats_example

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Check out repo
        uses: actions/checkout@v2
      - name: execute py script
        run: python plotting_and_stats_example.py
      # - uses: actions/upload-artifact@v3
      #   if: always()
      
